-- One-time load of the July-September 2026 micro monthly plan (generated by src/scripts/build-plan.ts; do not edit by hand).
-- 13 tracks, 52 workstreams, 125 sub tasks, 5 hurdles.
-- It only runs on an empty plan: if any item already exists the whole block is skipped, so a re-run or a
-- database that already holds data is never changed or duplicated.
DO $plan$
BEGIN
  IF EXISTS (SELECT 1 FROM "Item") THEN
    RAISE NOTICE 'Plan load skipped: the Item table already has rows.';
    RETURN;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM "Mission") THEN
    INSERT INTO "Mission" ("id", "name", "startDate", "targetDate", "originalTargetDate")
    VALUES ('43d6b53b-68da-5217-ac00-42261f1af0a8', 'Q1 Mission', '2026-07-01 00:00:00', '2026-09-30 00:00:00', '2026-09-30 00:00:00');
  END IF;

  INSERT INTO "Pillar" ("id", "letter", "name") VALUES
    ('c9be2fd6-2b9d-5f14-9c14-1fbe0c543d51', 'A', ''),
    ('ead05872-1793-5e7d-8d52-e579f60dad7a', 'B', ''),
    ('08f02f0f-4166-5380-88b2-1c08f8db7d33', 'C', ''),
    ('5b3729de-f5bd-5a6d-8d48-0617f45b4d27', 'D', ''),
    ('f8c446ff-b425-58fa-a4c3-a3062b6a3c7a', 'E', ''),
    ('58c27afc-f0af-54cf-9095-0490c9f13eff', 'F', ''),
    ('e3cf2c6e-3c01-59cc-930a-b11089b49560', 'H', ''),
    ('d4f6cd26-d790-517f-ad14-a1993df4c22d', 'I', '')
  ON CONFLICT ("letter") DO NOTHING;

  -- tracks
  INSERT INTO "Item" ("id", "title", "type", "parentId", "ownerName", "targetStartDate", "targetEndDate", "status", "weight", "parked", "parkedReason", "evidenceLinks", "pillarId", "remarks") VALUES
    ('61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Khel Setu - Identity Platform', 'PROJECT', NULL, 'Mansi', '2026-07-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'A'), NULL),
    ('826dd86f-fb42-5777-8462-033ae98ed73a', 'Training Centre Management', 'PROJECT', NULL, 'Gaurav', '2026-07-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'B'), NULL),
    ('f88b938b-01e5-5b38-bd0f-530039524830', 'ACTC', 'PROJECT', NULL, 'Gaurav', '2026-07-01 00:00:00', '2026-09-01 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'C'), NULL),
    ('b13a4a30-c8ce-5f8c-8e1a-64ea357ee331', 'Games Management System (GMS)', 'PROJECT', NULL, 'Yogita', '2026-07-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'C'), NULL),
    ('09e6f60d-7043-520c-aa5e-93d9645ea5fd', 'Grievance Redressal System', 'PROJECT', NULL, 'Gaurav', '2026-06-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'D'), NULL),
    ('0eaa0965-3bc1-555a-aaa5-1a6e6d49d1d3', 'Central Monitoring System', 'PROJECT', NULL, 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'D'), NULL),
    ('733122d2-5631-5d4a-84ad-add9e5195f38', 'MIS, Reports and Dashboard', 'PROJECT', NULL, 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'D'), NULL),
    ('7e7bf1e0-e248-59f5-a791-ad0e35590150', 'DBT and APBS — Entitlement Disbursement', 'PROJECT', NULL, 'Mansi', '2026-07-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'E'), NULL),
    ('1498c1d7-c96c-5568-87cb-612e81351b99', 'Sports Infrastructure Registry', 'PROJECT', NULL, 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'F'), NULL),
    ('5cb86958-7f14-524e-8218-1f95b51a47c1', 'Works Management System', 'PROJECT', NULL, 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'F'), NULL),
    ('4d2fa79d-baf8-5aaf-b304-0db591501148', 'Fit India Platform', 'PROJECT', NULL, 'Yogita', '2026-07-15 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'H'), NULL),
    ('1d22ced1-17b4-55f3-92e3-7080338a0716', 'Khelo India Website', 'PROJECT', NULL, 'Mansi', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'I'), NULL),
    ('860b6ee1-1a39-5922-a37b-4c9a092be9dc', 'Athlete Management System', 'PROJECT', NULL, NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', (SELECT "id" FROM "Pillar" WHERE "letter" = 'B'), NULL);

  -- workstreams
  INSERT INTO "Item" ("id", "title", "type", "parentId", "ownerName", "targetStartDate", "targetEndDate", "status", "weight", "parked", "parkedReason", "evidenceLinks", "pillarId", "remarks") VALUES
    ('96fed9ea-3092-5a0b-a78d-a8e33c167f85', 'Onboarding of PE Teachers', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-09-16 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('b5933a7d-7b94-55a8-b3d3-5f0cf22223c8', 'Admin Dashboard', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-09-09 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('f128ca23-6d31-5d08-9a27-81d502262b41', 'Onboarding (Tagging) of PCA in NSRS', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('b7d53094-f0d2-52db-94d4-967ca5f4e0e6', 'Provision of Foreign Coaches', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('10cd4e56-b2d7-504c-8959-7534e6c75ffa', 'Provision of NRI Athlete', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-08-31 00:00:00', 'TO_DO', 1, true, 'NRI Athlete to be discussed internally. As discussed in the meeting dated 21 Aug 2026 with DD IT DIv. SAI, it is suggested to park this', '{}', NULL, NULL),
    ('b733c704-0ecd-56a3-a9ab-28c5a59efd0b', 'Mapping of athletes, coaches, etc. with respective govt agencies (Army, Paramilitary, Railways, etc.)', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', NULL, NULL, 'TO_DO', 1, true, 'Mail sent to SAI for list on 10th September, 2026', '{}', NULL, NULL),
    ('ab0c7e9d-c1bc-506b-9526-f968554d19c4', 'Sport change of stakeholders', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('039555d6-e023-583c-9339-be09d0e33c6a', 'Role change of stakeholders', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'Discuss with IT Division to map the approving authority. To be picked up later post 12 Aug 2026, need disussion.', '{}', NULL, NULL),
    ('5508d502-eb2b-554e-9569-238be17c9da6', 'Athlete, Coach, Sports Science Data Filters', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-08-12 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('837c6a97-ce67-5678-a85d-3378ffe2bf08', 'Naming Convention', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', NULL, '2026-08-27 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('117a33f0-8140-5f2a-b32c-723381de7ab6', 'Onboarding of CDAC (AUA), SAI (as the Sub-AUA), NeGD as the System Integrator (SI) & Audit Compliance', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('989928c5-d742-55a4-a884-f2494252145e', 'Whatsapp Integration Plan', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-09-09 00:00:00', '2026-09-10 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('28ddb2fc-b05b-567b-b444-b1093cfc87ee', 'Aadhaar e-KYC', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-08-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('8ea95099-e40d-554c-9a3e-8dd2a8d74465', 'Integration of DBT with NSRS', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('db0d0a06-1717-555b-8a16-52d16a77e3cc', 'SSO implementation', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('f74e8460-1f4d-5620-8320-086647f49a2e', 'RBAC implementation', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Consent management', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('ddf80f4f-52e6-5f31-b6b5-5d1556c01c65', 'User Management', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('39f5b743-578f-51db-84b1-64c5acae1352', 'Data de-duplication', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('f2413019-b230-578b-bac3-69846cb66456', 'Notification Services', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('e1c56120-fba2-5765-9f78-3ec027f13dda', 'Data Migration', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', NULL, NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('5e652428-bbfe-5c4c-96b3-04ec59fd62f4', 'Workflow Engine', 'WORKSTREAM', '61ee46cc-8f60-5bd6-b9f4-3dd32a7746b4', 'Mansi', '2026-08-01 00:00:00', '2026-08-21 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('57a6f924-740c-5dd0-80ae-bf66435b429d', 'Centre onboarding & Accrediation', 'WORKSTREAM', '826dd86f-fb42-5777-8462-033ae98ed73a', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('534831a3-95f7-5313-873f-b96dd1fc5294', 'Talent Identification - Admission Process', 'WORKSTREAM', '826dd86f-fb42-5777-8462-033ae98ed73a', 'Gaurav', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('0af4508b-43d3-5223-89b1-18559cf34b2b', 'Counselling process for KIA /E- KIA', 'WORKSTREAM', '826dd86f-fb42-5777-8462-033ae98ed73a', 'Gaurav', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, true, 'Client has requested to Park this since the policies and workflows are awaited from their side', '{}', NULL, NULL),
    ('c1bc9ce4-4a61-5e68-81fc-ea48675ce674', 'ACTC improvisations', 'WORKSTREAM', 'f88b938b-01e5-5b38-bd0f-530039524830', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'No requirements have received from the client, a revamped version will be created at the later stage', '{}', NULL, NULL),
    ('ed964f57-edb0-50c4-be70-4413a973f54a', 'NSF Certificates Templates', 'WORKSTREAM', 'f88b938b-01e5-5b38-bd0f-530039524830', NULL, '2026-08-26 00:00:00', '2026-09-01 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('39b3e9d9-5707-57b0-86a5-ff745fa35c9a', 'Asian Games and CWG GMS improvisations', 'WORKSTREAM', 'b13a4a30-c8ce-5f8c-8e1a-64ea357ee331', 'Yogita', '2026-07-01 00:00:00', '2026-07-20 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('c60475e5-10ed-5cdc-8f8f-ef64259293b2', 'Khelo India Web', 'WORKSTREAM', 'b13a4a30-c8ce-5f8c-8e1a-64ea357ee331', 'Yogita', '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('ff2d1f11-9e11-5761-b726-7703a0818f38', 'Khelo india Mobile App', 'WORKSTREAM', 'b13a4a30-c8ce-5f8c-8e1a-64ea357ee331', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('3f78ecaa-24f1-5369-9d94-db7a1abf301b', 'Call Centre Integration', 'WORKSTREAM', '09e6f60d-7043-520c-aa5e-93d9645ea5fd', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('f8aad989-ae0f-5545-a05a-444a49423220', 'Athlete to ARM workflow', 'WORKSTREAM', '09e6f60d-7043-520c-aa5e-93d9645ea5fd', 'Gaurav', '2026-06-01 00:00:00', '2026-06-25 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('99f31626-5ab8-5a1e-98a2-c2d3db02adbd', 'Complete end to end Grievance modules for every SAI division specific', 'WORKSTREAM', '09e6f60d-7043-520c-aa5e-93d9645ea5fd', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('f3fd675c-154f-5e3b-b8ff-5ce3a0557a26', 'Monitoring System', 'WORKSTREAM', '0eaa0965-3bc1-555a-aaa5-1a6e6d49d1d3', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('f595f749-8ac3-5c91-b173-6988279cff2c', 'MIS Reports for Operations Division via RCMS', 'WORKSTREAM', '733122d2-5631-5d4a-84ad-add9e5195f38', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('a222b668-3d4b-5c9d-a6e8-a01ad907ac21', 'DBT Migration to new Server', 'WORKSTREAM', '7e7bf1e0-e248-59f5-a791-ad0e35590150', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('f498cf22-4097-5eff-896d-f7110afa2f9b', 'Existing Issues and Audit Issues (VAPT)', 'WORKSTREAM', '7e7bf1e0-e248-59f5-a791-ad0e35590150', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('69241a40-641e-513c-8fb2-214b55a11eda', '3 schemes live; PFMS integration', 'WORKSTREAM', '7e7bf1e0-e248-59f5-a791-ad0e35590150', 'Mansi', '2026-07-29 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('15e63811-b35b-5c3f-943e-585e1ebdeb2d', 'National Infra Facility Registry (Web)', 'WORKSTREAM', '1498c1d7-c96c-5568-87cb-612e81351b99', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('3b5ff384-ffcf-5d1e-99fd-d3acc2aac3ea', 'National Infra Facility Registry (App)', 'WORKSTREAM', '1498c1d7-c96c-5568-87cb-612e81351b99', NULL, NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('c26ba243-2e0d-568d-8001-296154085a16', 'GIS Mapping and Visualisation', 'WORKSTREAM', '1498c1d7-c96c-5568-87cb-612e81351b99', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('32ce9858-4bfd-5923-93cc-08051abe2727', 'Registry Maintenance and Governance', 'WORKSTREAM', '1498c1d7-c96c-5568-87cb-612e81351b99', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('1883b50c-0e49-5c0d-b950-a751103621f0', 'Works Management System (Phase 1)', 'WORKSTREAM', '5cb86958-7f14-524e-8218-1f95b51a47c1', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('b88e7d83-967b-5f2c-8f91-864e43d4a4d0', 'Fit India Mobile Application Improvisations', 'WORKSTREAM', '4d2fa79d-baf8-5aaf-b304-0db591501148', 'Yogita', '2026-07-15 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('ab16e9f5-d863-5aa9-b353-d5d406b66aa5', 'Fit India New Mobile Application - Phase 1', 'WORKSTREAM', '4d2fa79d-baf8-5aaf-b304-0db591501148', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('3a48acb0-8922-5e0b-8825-43d1ee1280ce', 'Khelo India Website Phase 2: a.) Individual State/UT Page', 'WORKSTREAM', '1d22ced1-17b4-55f3-92e3-7080338a0716', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('38fa0c2c-c666-52f3-933d-9d95eb3f3caa', 'Khelo India Website Phase 2: b.)Athletes Page', 'WORKSTREAM', '1d22ced1-17b4-55f3-92e3-7080338a0716', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('2c7dde40-6748-5bed-91a0-b6de4e396f81', 'Khelo India Website Phase 2: c.)Selection Trials Page', 'WORKSTREAM', '1d22ced1-17b4-55f3-92e3-7080338a0716', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('d69968f8-d61e-5346-93b4-985eb5c45ca9', 'Khelo India Website Phase 2: d.) Careers Page', 'WORKSTREAM', '1d22ced1-17b4-55f3-92e3-7080338a0716', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('b1b46c85-bbbf-58e2-aa2c-e6fd2b7d7e53', 'Khelo India Website Phase 2: e.) Dashboard', 'WORKSTREAM', '1d22ced1-17b4-55f3-92e3-7080338a0716', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('820688a7-c6e6-58b1-b9c3-20e51c762c04', 'Nutrition Module', 'WORKSTREAM', '860b6ee1-1a39-5922-a37b-4c9a092be9dc', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', 'Biochemistry Module', 'WORKSTREAM', '860b6ee1-1a39-5922-a37b-4c9a092be9dc', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL);

  -- sub tasks
  INSERT INTO "Item" ("id", "title", "type", "parentId", "ownerName", "targetStartDate", "targetEndDate", "status", "weight", "parked", "parkedReason", "evidenceLinks", "pillarId", "remarks") VALUES
    ('c9ae2435-e784-586c-b91f-dc2b26f68cc8', '1. Registration of Physical education teachers in NSRS using digilocker services', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed to Production
Remarks from the SAI team: Deployed in Production.
Actual completion: 7 Jul 2026'),
    ('c1874b74-0223-5da9-a453-239fde0384c1', '2. PE Teachers Profile creation in NSRS of PE Teachers - Personal and Education and other details to be filled', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed in Production.
Remarks from the SAI team: Deployed in Production.
Actual completion: 31 Jul 2026'),
    ('e5250d5e-d1df-5908-853f-f7b16e54c1bd', '3. Improvisations in the profile as suggested by LNIP', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', NULL, '2026-09-02 00:00:00', '2026-09-09 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('62100abf-8754-5458-b394-91a347c93ae3', '4. UDISE integration for PE teachers', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, 'Remarks: Mail sent by SAI to Ministry of Education for incorporating USIDE APIs'),
    ('4784ecd0-4647-56de-8919-387ab5118c0a', '5. PE teacher module enhancement – institute type selection, district filter, etc.', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', 'Mansi', '2026-09-11 00:00:00', '2026-09-16 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Code Deployed to UAT'),
    ('ca83e044-c928-5918-b7e3-e4c0b822aa50', 'DG Review Meeting', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', NULL, NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('e35a5b18-3beb-56c9-99e6-7123275f2534', 'JS Review', 'TASK', '96fed9ea-3092-5a0b-a78d-a8e33c167f85', NULL, NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('9f4f6ac0-6cff-52bc-b378-0583cbc9315e', '1. All registration Data to be displayed in Admin Dshboard with all the information taken during registration process', 'TASK', 'b5933a7d-7b94-55a8-b3d3-5f0cf22223c8', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed in Production.
Remarks from the SAI team: Deployed in Production.
Actual completion: 13 Aug 2026'),
    ('c172039c-d644-5303-9156-7a412034fe2d', '2. Improvisations in the Dashboard as suggested by LNIP', 'TASK', 'b5933a7d-7b94-55a8-b3d3-5f0cf22223c8', NULL, '2026-09-02 00:00:00', '2026-09-09 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed in Production.'),
    ('289191e8-3537-5ad4-b323-5a14f3b03460', '1. Mapping of PCA in NSRS and a tag to be put in NSRS in their profile', 'TASK', 'f128ca23-6d31-5d08-9a27-81d502262b41', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed in Production.
Remarks from the SAI team: Deployed in Production.
Actual completion: 31 Jul 2026'),
    ('666291ea-7638-506a-9134-26db7f9eacef', '1. Registration through mobile no to be introduced for foreign coaches in NSRS', 'TASK', 'b7d53094-f0d2-52db-94d4-967ca5f4e0e6', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Foreign Coach registration via mobile number has been deployed to production
Remarks from the SAI team: Foreign Coach registration via mobile number has been deployed to staging'),
    ('b5af0d50-e5af-5703-b9d1-38b440e44062', '2. Profile creation and updation', 'TASK', 'b7d53094-f0d2-52db-94d4-967ca5f4e0e6', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Deployed in Production.'),
    ('a514b9c4-1599-56a6-93e0-385518d7f48d', '1. Registration of NRI Athletes through mobile no or other sources to be introduced in NSRS (Sports Passport) to be applicable later', 'TASK', '10cd4e56-b2d7-504c-8959-7534e6c75ffa', 'Mansi', '2026-07-01 00:00:00', '2026-08-31 00:00:00', 'TO_DO', 1, true, 'NRI Athlete to be discussed internally. As discussed in the meeting dated 21 Aug 2026 with DD IT DIv. SAI, it is suggested to park this', '{}', NULL, 'Remarks: NRI Athlete to be discussed internally.
As discussed in the meeting dated 21 Aug 2026 with DD IT DIv. SAI, it is suggested to park this
Remarks from the SAI team: Started To Create API for Registration, with no changes in Existing Data Capture'),
    ('8386e783-60f7-56e9-a883-b9bb8bd526b3', 'List of registered athletes to be received from IT Division, then tagging will be done from backend', 'TASK', 'b733c704-0ecd-56a3-a9ab-28c5a59efd0b', 'Mansi', NULL, NULL, 'TO_DO', 1, true, 'Mail sent to SAI for list on 10th September, 2026', '{}', NULL, 'Remarks: Mail sent to SAI for list on 10th September, 2026'),
    ('83c6b8a4-b62e-5a9c-b795-ba1b8823f8f1', '1. Impact analysis to the downstream applications - GMS, ACTC, AMS, etc.', 'TASK', 'ab0c7e9d-c1bc-506b-9526-f968554d19c4', NULL, '2026-08-27 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('ad480d42-33cb-50a6-9c52-b76f0bff9494', '2. Multiple sports selction and mapping in NSRS for athletes', 'TASK', 'ab0c7e9d-c1bc-506b-9526-f968554d19c4', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, 'Remarks: To be picked up later post impact analysis.'),
    ('97beb5bb-9d34-58e8-8315-192926d8d1c2', '1. Role change of stakeholders like athlete to coach, coach to technical official in nsrs', 'TASK', '039555d6-e023-583c-9339-be09d0e33c6a', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'Discuss with IT Division to map the approving authority. To be picked up later post 12 Aug 2026, need disussion.', '{}', NULL, 'Remarks: Discuss with IT Division to map the approving authority. To be picked up later post 12 Aug 2026, need disussion.'),
    ('ac974350-9404-5054-91b0-d58779381b7c', '1. Athlete - NSRS ID, Name, State, sport,Academy, KIA, TOPS (core and Developmental) Sanction, Aadhaar verified', 'TASK', '5508d502-eb2b-554e-9569-238be17c9da6', 'Mansi', '2026-08-12 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Timeline has exceeded due to non availability of frontend developer at SAI, Also omendra has informed Antik sir regarding this.
Remarks from the SAI team: Deployed in Production.
(This row of the plan listed 4 sub tasks in one cell; these remarks cover all of them.)'),
    ('d20b812a-85cd-5df1-9c02-417ca4a612e4', '2. Coach - NSRSID, Name, Sports, Academy, State', 'TASK', '5508d502-eb2b-554e-9569-238be17c9da6', 'Mansi', '2026-08-12 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('81eb1d3f-32b6-5509-b1c3-98ce8b9d4915', '3. Sports scientist - NSRSID, Name, Category, Academy', 'TASK', '5508d502-eb2b-554e-9569-238be17c9da6', 'Mansi', '2026-08-12 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('1fbb76b5-efb9-59f4-ab5e-bc35c21ac45e', '4. Academy - NSRS ID, Name, Sports, Type, Athlete(no and listing to be shown), Coachno and listing to be shown), Sports Scientistno and listing to be shown), STATE, KIAA', 'TASK', '5508d502-eb2b-554e-9569-238be17c9da6', 'Mansi', '2026-08-12 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('c1483894-d5db-5907-ad37-410bc1a5b031', '1. Change the Naming Convention (NSRS ID -> NSRS (Khel ID)', 'TASK', '837c6a97-ce67-5678-a85d-3378ffe2bf08', NULL, '2026-08-27 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('1c77c221-f6bf-511c-b646-e73a14afb04e', '1. Compliance sheet to be filled', 'TASK', '117a33f0-8140-5f2a-b32c-723381de7ab6', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: SAI IT Team currently on filling in the compliance sheet and making NSRS compliant as per the mentioned norms.
Remarks from the SAI team: All the features are available on the staging server:

Voice-enabled CAPTCHA has been implemented on the login page.
Password attempt limit (account lockout mechanism) has been implemented.
Users cannot reuse any of their last three passwords.
IP address logging is currently in progress.
Password expiration has been set to 90 days. Additionally, if an academy administrator resets a user''s password, the user will be required to change it upon their first login. The backend implementation is complete; the UI changes are pending.'),
    ('98a15050-8b38-5b28-8959-a816f6d7bafc', '2. Security audit of the entire NSRS based on the complaince sheet', 'TASK', '117a33f0-8140-5f2a-b32c-723381de7ab6', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('8c18ce32-bc71-512e-907f-7eff8b9afb2f', '3. Implementation of adhaar APIs provided by CDAC', 'TASK', '117a33f0-8140-5f2a-b32c-723381de7ab6', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('355dc5e6-f514-522f-b144-26406b795d08', 'Define Scope', 'TASK', '989928c5-d742-55a4-a884-f2494252145e', 'Mansi', '2026-09-09 00:00:00', '2026-09-09 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Scope Document'),
    ('86dd1a87-07ac-57cd-9a31-0e28c235f448', 'Prepare RFQ', 'TASK', '989928c5-d742-55a4-a884-f2494252145e', 'Mansi', '2026-09-09 00:00:00', '2026-09-10 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: RFQ'),
    ('39102fd3-e6f5-5bab-83b6-8bc4260a093b', 'Integration', 'TASK', '989928c5-d742-55a4-a884-f2494252145e', NULL, NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('64abd664-1c78-54c1-9cae-d8dc075ddc6a', '1. Testing and implementation', 'TASK', '28ddb2fc-b05b-567b-b444-b1093cfc87ee', 'Mansi', '2026-07-01 00:00:00', '2026-08-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('19148960-d05e-5613-931c-8d45fc037277', '1. Migration of Existing DBT to new infra', 'TASK', '8ea95099-e40d-554c-9a3e-8dd2a8d74465', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, 'Remarks: Infrastructure Procurement Bid Floated'),
    ('f009c705-fcbe-58a0-920a-d3db098f4180', '1. Backend development for SSO', 'TASK', 'db0d0a06-1717-555b-8a16-52d16a77e3cc', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Backend implementation completed
Actual completion: 30 Jul 2026'),
    ('e8f4d29d-f2cf-5940-a33e-f1d971105eff', '2. Login design and development', 'TASK', 'db0d0a06-1717-555b-8a16-52d16a77e3cc', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Actual completion: 31 Jul 2026'),
    ('297f67bd-0c1e-5ea4-a1a6-9de7f19a4d2b', '3. Profile design and development', 'TASK', 'db0d0a06-1717-555b-8a16-52d16a77e3cc', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('26cc2327-5bc1-5e0b-aa64-8bd9dd4a78b0', '4. Home Page design and development', 'TASK', 'db0d0a06-1717-555b-8a16-52d16a77e3cc', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Actual completion: 31 Jul 2026'),
    ('1d11c6cd-88a9-5706-a39f-15a645510864', '1. Defining Roles and Module Access Design', 'TASK', 'f74e8460-1f4d-5620-8320-086647f49a2e', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: Backend implementation completed
Actual completion: 31 Jul 2026'),
    ('d18171c1-108d-5b09-8ead-a73ebd51071e', '2. Backend development', 'TASK', 'f74e8460-1f4d-5620-8320-086647f49a2e', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Actual completion: 31 Jul 2026'),
    ('eff2e799-2c6c-537f-9c31-8c5d812869e0', '1.Record of consent of the Aadhaar number holder for authentication', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('7fc1ae4d-9629-55a9-96a4-847a9a7ba08d', '2.Record of disclosure of information to the Aadhaar number holder at the time of authentication.', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('091a772a-c805-5350-83d1-8ad50185b896', '3.Child consent Form', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('69fc9bf8-c276-5c1d-a88d-e4588f631366', '4.Consent logs', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('34c3c0a3-fb2b-58a4-90af-382d67a32285', '5. Mechanism to communicate consent with people with disability', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('2feac8b8-9edc-5365-bb86-72eb833c14c2', '6. Local language consent content', 'TASK', '00b3e9a6-9b7d-5959-b61f-87b2a695f119', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('f2b49810-c53a-5497-8be0-e269a1214d3f', '1. Implementation of User Management', 'TASK', 'ddf80f4f-52e6-5f31-b6b5-5d1556c01c65', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Actual completion: 31 Jul 2026'),
    ('6772bf91-f5d8-5bb5-b390-4ab77a818c41', '1. Data dump extraction and identification of parameters on which duplication can be removed', 'TASK', '39f5b743-578f-51db-84b1-64c5acae1352', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, 'Remarks: Should this be done on NSRS or NSDE? To be confirmed with Vinay Sir. As per Mayank, this can not be achieved by 31 July'),
    ('e622702a-2183-5111-8ebc-5cad9fda751c', '1. SMTP details from CDAC', 'TASK', 'f2413019-b230-578b-bac3-69846cb66456', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('9853648b-d556-57dd-b847-ec9b22522ebe', '1. Approach Note for Worklfow Engine', 'TASK', '5e652428-bbfe-5c4c-96b3-04ec59fd62f4', 'Mansi', '2026-08-01 00:00:00', '2026-08-15 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Actual completion: 15 Aug 2026'),
    ('d74472ee-505d-585b-b10d-f705bbdc471a', '2. Development for Workflow Engine as a service', 'TASK', '5e652428-bbfe-5c4c-96b3-04ec59fd62f4', 'Mansi', '2026-08-18 00:00:00', '2026-08-21 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('8f05d446-aaa5-5b00-9bfe-a5a077ffe7bc', '1. Centre onboarding & Accrediation', 'TASK', '57a6f924-740c-5dd0-80ae-bf66435b429d', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Gaurav to start BRD from 31 Aug 2026 along with Piyush'),
    ('e97dba1e-0d06-5dde-ae1d-c164c556fe3a', '1. Admission Process - Athletes Induction and weedout to be done by ARM, Centre head, Athletes, Administration( AD/DD/Director/ED)', 'TASK', '534831a3-95f7-5313-873f-b96dd1fc5294', 'Gaurav', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: BRD to be finalized and signed - off by 7 Aug 2026'),
    ('d99d9842-cdb3-5016-bdca-cdec65918d7a', '1. Centrewise performance report of athletes', 'TASK', '0af4508b-43d3-5223-89b1-18559cf34b2b', 'Gaurav', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, true, 'Client has requested to Park this since the policies and workflows are awaited from their side', '{}', NULL, 'Remarks: Client has requested to Park this since the policies and workflows are awaited from their side'),
    ('4b2454c1-95fc-5a3d-ab0b-965189a9f0b8', '2. Academy allotment/ transfer request', 'TASK', '0af4508b-43d3-5223-89b1-18559cf34b2b', 'Gaurav', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, true, NULL, '{}', NULL, NULL),
    ('8dcf45e1-88a1-52b1-a945-aa62c91174d3', '1. Stakeholder consultation based on new changes to be done in portal', 'TASK', 'c1bc9ce4-4a61-5e68-81fc-ea48675ce674', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'No requirements have received from the client, a revamped version will be created at the later stage', '{}', NULL, 'Remarks: No requirements have received from the client, a revamped version will be created at the later stage
(This row of the plan listed 3 sub tasks in one cell; these remarks cover all of them.)'),
    ('56e2f553-d2fa-5105-afb9-609a6eb3cad0', '2. Calendar and Proposal changes', 'TASK', 'c1bc9ce4-4a61-5e68-81fc-ea48675ce674', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'No requirements have received from the client, a revamped version will be created at the later stage', '{}', NULL, NULL),
    ('7dc29fd8-bf0c-588a-98ff-a794f9d419a8', '3. Sanctions updation', 'TASK', 'c1bc9ce4-4a61-5e68-81fc-ea48675ce674', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'TO_DO', 1, true, 'No requirements have received from the client, a revamped version will be created at the later stage', '{}', NULL, NULL),
    ('19f7a8dc-1e49-51c7-b60d-e3a93f08c209', '1. Excel template for NSF to upload data of athletes', 'TASK', 'ed964f57-edb0-50c4-be70-4413a973f54a', NULL, '2026-08-26 00:00:00', '2026-09-01 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('91a02815-a45c-58c3-a4cc-ccd0a92b3fa2', '2. API integration with digilocker', 'TASK', 'ed964f57-edb0-50c4-be70-4413a973f54a', NULL, '2026-08-26 00:00:00', '2026-09-01 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('2db9f61a-ba82-5066-9b54-7a5f9f4dac73', '1. HTML creation based on the excel provided by divsion', 'TASK', '39b3e9d9-5707-57b0-86a5-ff745fa35c9a', 'Yogita', '2026-07-01 00:00:00', '2026-07-20 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('3bf1687a-923d-5236-b599-2588df023fa6', '2. Appication creation based on the html approval by division', 'TASK', '39b3e9d9-5707-57b0-86a5-ff745fa35c9a', 'Yogita', '2026-07-01 00:00:00', '2026-07-20 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('9b144864-80cd-5501-8279-ee9c050ca3be', '1. Setup of GMS based on the new games', 'TASK', 'c60475e5-10ed-5cdc-8f8f-ef64259293b2', 'Yogita', '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('46381120-c26f-59e8-a0cd-aeab96396571', '2. TSR Integration and setup of scoring', 'TASK', 'c60475e5-10ed-5cdc-8f8f-ef64259293b2', 'Yogita', '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('fc47ae1b-ef2e-576a-8cdc-242f4dfe0280', '3. ACT Module to be ready before the games', 'TASK', 'c60475e5-10ed-5cdc-8f8f-ef64259293b2', 'Yogita', '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('d475a488-e597-5452-84e0-c2f7f624b12a', '1. Top medalist', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('ddd77e65-f4a7-5ee6-ac84-537f6925fa5d', '2. Top home banner', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('1d9495dc-4093-599a-bf8e-633436792167', '3. Archery score screen', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('d1c02807-7418-54d2-8f36-9474a7001ab3', '4. Bus Details', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('a65e55eb-2582-5f99-aac4-3bc89912d807', '5. Catering', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('7781cbd2-c419-57e0-8144-1e6c04238c85', '6. Grievance', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('bbaaffc1-5efa-5a16-9365-c799b195c013', '7. App logo according to app colors theme', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('8bd21813-9de1-5af0-b8f4-e4fdf6ac0552', '8. CDM/UCM login', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('3d8b082c-8487-5d60-9816-a5a40ffd4cb3', '9. Kit distribution dashboard flow', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('fcb59a2e-e917-55db-9e0b-1d4e2282701e', '10. Accred dashboard flow', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('5c7e7c1a-79a1-5516-bd5f-39f31df3c5d6', '11. Super admin flow', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('5588506a-d2f6-5b0c-b20c-db69cf2a6823', '12. Accommodation manager related flow', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('c6169d30-c14e-5762-92bb-e9396b46fb6b', '13. Icon nav bar related', 'TASK', 'ff2d1f11-9e11-5761-b726-7703a0818f38', NULL, '2026-09-01 00:00:00', '2026-11-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('c5a073b4-3614-5761-9f1e-888bb0a8ed1a', '1. CRM Integration with the existing call centre', 'TASK', '3f78ecaa-24f1-5369-9d94-db7a1abf301b', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('1b9ca8ff-fe19-59b6-a7af-80fcce8a092a', '1. Design creation of the flow', 'TASK', 'f8aad989-ae0f-5545-a05a-444a49423220', 'Gaurav', '2026-06-01 00:00:00', '2026-06-25 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('4cfdceb1-1fcf-5971-87e1-71c44dc27d1a', '2. Athlete to ARM flow and back flow', 'TASK', 'f8aad989-ae0f-5545-a05a-444a49423220', 'Gaurav', '2026-06-01 00:00:00', '2026-06-25 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('60d191e8-8ea5-5aad-a5d9-124e0febd2cc', '1. Prepared the BRD and Detailed concept note on the grievance module and a PPT for the same', 'TASK', '99f31626-5ab8-5a1e-98a2-c2d3db02adbd', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('c2ab27bd-b116-57f7-820c-25d19f07cb6f', '1. Meeting with Shambhoo sir, Regarding the Monitoring app process flows and prepared a HTML prototype of the Monitoring app', 'TASK', 'f3fd675c-154f-5e3b-b8ff-5ce3a0557a26', 'Gaurav', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks from the SAI team: BRD to be shared by 10 Aug 2026.'),
    ('2ac607b0-3cc4-5e16-91ab-ed0eb2f646ac', '1.Meeting with the Ops division and showed them the HTML for the Monitoring system, and the Dashboard Documentation(FRD) is done for the same. RCMS Portal delivered to Ops Division on 31 July 2026 for User Acceptance Testing (UAT).', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, 'Remarks: This has been delivered to Ops Division on 31 July 2026, Demo has been given to DD & AD IT as well as Direcotor Ops Div (Shri. Manikant)
Imrovisations are being carried out as per DDG Ma''am feedback. Dev to be completed by 20 Aug 2026.
Actual completion: 31 Jul 2026
(This row of the plan listed 10 sub tasks in one cell; these remarks cover all of them.)'),
    ('d4a71e02-c6ef-5299-8ac4-478e03769c75', '2.Demo/Walkthrough conducted for DD & AD IT and Director, Ops Division (Shri Manikant Sharma).', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('2170d9b3-c8e2-5332-bf87-890955650520', '3.Improvements/enhancements initiated based on feedback received from DDG Ma’am, with development targeted for completion by 20 August 2026.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('aefcb88c-df35-5246-b8cc-92dd24b77df6', '4.Meeting conducted with DDG, Ops Division on 7 September 2026 to review the implemented improvements. Further suggestions were provided, including:', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('781e00ec-b451-55e2-8083-c323448eb21c', '5.Creation of a new Coach Profile template under Quarterly Templates.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('37687ff0-8ca0-50b4-b1d6-65ba74bcc4e4', '6.Addition of Competition Type and Periodicity fields in the Foreign Exposure template under Monthly Templates.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('3d75af6f-5712-56df-97ab-af2ae3eca48e', '7.Addition of a Discipline dropdown on the dashboard.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('7f6ae783-76a5-5602-90ff-3b387ef61dc9', '8.Revamp of the UI/theme for all templates, with a vibrant and consistent colour family across the templates.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('2c9a0601-ae72-54b2-9ff5-47052b35df95', '9.Changes and UI enhancements implemented and presented to DDG Ma’am on 10 September 2026 for review.', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('0a894425-355f-5d50-bb59-15025e7e9f10', '10.Updated design approved by DDG Ma’am on 10 September 2026, based on the discussed enhancements and UI changes.1. Meeting with the Ops division and showed them the HTML for the Monitoring system, and the Dashboard Documentation(FRD) is done for the same', 'TASK', 'f595f749-8ac3-5c91-b173-6988279cff2c', 'Gaurav', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'LIVE', 1, false, NULL, '{}', NULL, NULL),
    ('308d8e1f-99ad-5c55-810c-b3c3ad560b81', '1. DBT Migration to new Server', 'TASK', 'a222b668-3d4b-5c9d-a6e8-a01ad907ac21', 'Mansi', '2026-07-01 00:00:00', '2026-07-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Infra awaiting bid query responses'),
    ('8e3c767f-090a-56be-8ec5-7e799ae91591', '2. VAPT Audit and Patching', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('3d8b458c-1a61-59e3-9582-13a4662c800f', '3. Sms account to be migrated from sp4 to khelo india account for DBT', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', '2026-09-03 00:00:00', NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('888c31cd-5668-5761-aac4-a3fa2be32e5b', '4. Sign off on the DBT proposed Flow', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', '2026-07-29 00:00:00', NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('ac2b38dd-292d-55c3-b3ea-c23da0eafdff', '5. Decision on whether the portal will be hosted on different domain - Same Domain', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('7be4f3fc-ebc3-57b0-a294-4287f8da98c3', '6. Designing for the process flow and it''s integration with the New platform', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('1525a9eb-4a9b-5d14-a6e3-5c10b7abaae0', '7. Templatising for all schemes', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', NULL, NULL, 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('567d389d-84b2-58de-b2da-2c1430dc5174', '8. Development for the all schemes and their hierarchial flows', 'TASK', '69241a40-641e-513c-8fb2-214b55a11eda', 'Mansi', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('e9cc400a-669d-5e62-ae44-6acd06b49bdc', '1. Prepared the Infra Registry and matching it to our database schema', 'TASK', '15e63811-b35b-5c3f-943e-585e1ebdeb2d', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Scope Of Phase 1 for Infra Registry Management 
1. Only Entry of record will be from RC ADMIN, So for all records currently getting entered will be in a APPROVED state as per workflow.
2. All "Approved" records across application will be displayed to SAI HO. (So may be no work flow engine required this point)
3. SAI HO will have option to PUBLISH/REJECT option for now. 
4. RC ADMIN will see all related data entered within scope with STATUS.

Workflow Engine to be incorporated later.
Remarks from the SAI team: BRD to be finalized by 7 Aug 2026
User Stories to be created by 10 Aug 2026
Design is in In Progress, First Draft to be shared by 7 Aug 2026
MVP 1 is completed, Demo to be planned with Eng. Division on 10-Sep-2026.
Entry Operator flow to be on Hold as per discussion on 10-Sep-2026
Field Level changes are shared by client. FRD to be updated by 11-Sep-2026 (EOD), Change Request to be created.'),
    ('d0f1c521-531e-5f65-8bcc-01e3c72c519e', '1. Integrating to the PM GatiShakti for mapping the Infra', 'TASK', 'c26ba243-2e0d-568d-8001-296154085a16', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('c71cf69f-85b8-5c04-9cd8-e1d43a73e374', '1. Registry creation, validation and approval of the Infra profiling- Prepared the FRD', 'TASK', '32ce9858-4bfd-5923-93cc-08051abe2727', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('a35917a7-b85b-5c39-ba30-e9a5699f9dab', '2. Create a prototype of the mobile application', 'TASK', '32ce9858-4bfd-5923-93cc-08051abe2727', 'Yogita', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('95b6a437-6866-50e7-944b-707e008a78b6', '1. Prepared the BRD of the WMS Flow', 'TASK', '1883b50c-0e49-5c0d-b950-a751103621f0', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, 'Remarks: Development will be Completed by today 9 September 2026 and It will be moved to UAT by today itself
Remarks from the SAI team: Testing completed till In Principle Approval. 
Demo for MVP 1 is planned at 2 pm with Eng. Division. 
Changes received in MVP 1, Revised FRD shared
(This row of the plan listed 2 sub tasks in one cell; these remarks cover all of them.)'),
    ('ef370a3b-16b3-5b68-a617-ec79b4c297bd', '2. Working on creating the prototype of WMS', 'TASK', '1883b50c-0e49-5c0d-b950-a751103621f0', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('e792e5a1-6da6-5cdb-b562-0b1919bd1acc', '1. Shared the bug list with the existing team to make changes and tieline is 10 days.', 'TASK', 'b88e7d83-967b-5f2c-8f91-864e43d4a4d0', 'Yogita', '2026-07-15 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('016bbdfc-9af7-5885-beca-0312afe9f038', '2. Need to make changes in the website also changes to be discussed with nisha mam.', 'TASK', 'b88e7d83-967b-5f2c-8f91-864e43d4a4d0', 'Yogita', '2026-07-15 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('de082670-5420-5e04-b344-077b4e364bb2', '1. Development of new Website', 'TASK', 'ab16e9f5-d863-5aa9-b353-d5d406b66aa5', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks from the SAI team: Plan a meeting with  the FIT India Team (Design, Dev, BA, QA)
(This row of the plan listed 4 sub tasks in one cell; these remarks cover all of them.)'),
    ('0996322e-7a30-5a4d-a094-0d6542cd48d7', '2. Working on the BRD document to list down all the features of FIT INDIA Application.', 'TASK', 'ab16e9f5-d863-5aa9-b353-d5d406b66aa5', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('0e0fcb39-1e63-5ed2-82ed-e87ac15dae9d', '3. Will Work on FRD of FIT INDIA Application', 'TASK', 'ab16e9f5-d863-5aa9-b353-d5d406b66aa5', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('4f385216-a8ed-58ad-b786-1edba21993ea', '4. Prepare the prototype of the Application.', 'TASK', 'ab16e9f5-d863-5aa9-b353-d5d406b66aa5', 'Yogita', '2026-08-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, NULL),
    ('e1776d4d-482a-5965-b327-6ff9e8041e86', 'Design and Develpoment', 'TASK', '3a48acb0-8922-5e0b-8825-43d1ee1280ce', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Waiting for first level launch'),
    ('9417d58c-2ceb-5815-b2e3-2a07f4438db7', 'Design and Develpoment', 'TASK', '38fa0c2c-c666-52f3-933d-9d95eb3f3caa', 'Mansi', '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Waiting for first level launch'),
    ('e7ad38eb-17d1-51fb-af1a-e229a895042f', 'Design and Develpoment', 'TASK', '2c7dde40-6748-5bed-91a0-b6de4e396f81', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Waiting for first level launch'),
    ('2cf014ab-944e-54ec-abb9-d4845a80123a', 'Design and Develpoment', 'TASK', 'd69968f8-d61e-5346-93b4-985eb5c45ca9', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Waiting for first level launch'),
    ('dd12a620-b4ad-5f7b-8dc0-a933925e1dc0', 'Design and Develpoment', 'TASK', 'b1b46c85-bbbf-58e2-aa2c-e6fd2b7d7e53', 'Mansi', '2026-08-01 00:00:00', '2026-08-31 00:00:00', 'DOING', 1, false, NULL, '{}', NULL, 'Remarks: Waiting for first level launch'),
    ('e25d9b53-0ab5-5527-b730-a2b1b46330df', 'Nutrition HPA and PA', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('93bc2afc-2664-50e6-b951-65abdbb71712', 'Dashboard Planning', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('3e361066-47eb-514d-897b-01fc23b1876c', 'Batch List', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('3d97f482-9e01-5821-878e-a09617451932', 'My Batch', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('9f047b28-21f8-58e0-8228-f93124535274', 'Diet Plan Templates', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('e13ef80f-54d2-5794-9099-e276a834a11e', 'Appointments', 'TASK', '820688a7-c6e6-58b1-b9c3-20e51c762c04', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('e0d3d36e-a9ae-5e58-b41a-ab7e6e2fc652', 'Biochemistry HPA and PA', 'TASK', '0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('ca99baa7-6cdf-5bca-bbc4-39aa4a6c206d', 'Dashboard Planning', 'TASK', '0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('fd689a14-bb87-5df9-92e4-bb4b29f2e9c9', 'Batch List', 'TASK', '0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('ee25e7ce-dee3-5070-a2eb-2b72bd0dd117', 'My Batch', 'TASK', '0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL),
    ('77f59301-da81-5da2-bb3e-21edee1eacc2', 'Biochemistry Reports', 'TASK', '0851efa7-10d9-5a70-b5b9-9d2c2da2ca97', NULL, '2026-09-01 00:00:00', '2026-09-30 00:00:00', 'TO_DO', 1, false, NULL, '{}', NULL, NULL);

  -- blockers raised for rows the plan marks Blocked
  INSERT INTO "Hurdle" ("id", "itemId", "text", "whoClears", "ownerNameBody") VALUES
    ('995a5cc5-30df-55f7-841a-5c78be38d353', 'e1776d4d-482a-5965-b327-6ff9e8041e86', 'Blocked: Waiting for first level launch', 'UNOWNED', 'Mansi'),
    ('852d4d3b-547d-55d9-9bc6-7ff25c112bb1', '9417d58c-2ceb-5815-b2e3-2a07f4438db7', 'Blocked: Waiting for first level launch', 'UNOWNED', 'Mansi'),
    ('f4251fd4-d89f-5947-aec4-2186f1ca42f9', 'e7ad38eb-17d1-51fb-af1a-e229a895042f', 'Blocked: Waiting for first level launch', 'UNOWNED', 'Mansi'),
    ('430d4a56-9b3a-5602-bcb0-df39e12ae94e', '2cf014ab-944e-54ec-abb9-d4845a80123a', 'Blocked: Waiting for first level launch', 'UNOWNED', 'Mansi'),
    ('3898c4f0-f7ef-5ce0-886c-ae72e047aac7', 'dd12a620-b4ad-5f7b-8dc0-a933925e1dc0', 'Blocked: Waiting for first level launch', 'UNOWNED', 'Mansi');

  INSERT INTO "ActivityLog" ("id", "who", "what", "after") VALUES
    ('93d9bb5c-ddeb-5f54-a77e-0613598b59c5', 'system (plan load migration)', 'Loaded the July-September 2026 micro monthly plan: 13 tracks, 52 workstreams, 125 sub tasks', '{"tracks":13,"workstreams":52,"tasks":125,"parkedTasks":8,"blockedTasks":5}'::jsonb);
END
$plan$;
